"""add role coloumn to users

Revision ID: 83c2828fa2e1
Revises: 
Create Date: 2026-08-13 20:47:37.318410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c2828fa2e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('product_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('order_items_quantity_check'), type_='check')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('order_items_quantity_check'), 'quantity > 0')
        batch_op.alter_column('product_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)

    # ### end Alembic commands ###
